### ISSUE TITLE
JAMF API Invitation Creation

### ISSUE THREAD

**Issue by tostart-pickagreatname** [PixarAnimationStudios/ruby-jss#14]
Hey @glenfarclas17,

Feel free to close this issue, but I wanted to mention that I found creation of new invitations via the API to be a dead end. This was due largely to the fact that values like the management account password associated with the invitation does not appear possible. This is obviously a significant barrier to leveraging this. My workaround has been to use a single, non-expiring invitation ID for all of my registrations.

Anyways, just thought I'd tie up this potential loose end since it might have some impact on how users use this class, and may suggest that we don't want invitations to be creatable within ruby-jss.

Cheers!

**Comment by glenfarclas17** [comment]
finally closing this :-)   thanks for the report last year!
