### ISSUE TITLE
Network segment membership is misscalculated

### ISSUE THREAD

**Issue by Bearzooka** [PixarAnimationStudios/ruby-jss#15]
The membership of computers to **Class A** or **Class B** Network Segments defined in JSS is miscalculated. 

When the function `JSS::NetworkSegment.my_network_segment` runs on a computer that has an IP address that belongs to a Class A or Class B Network Segment the resulting array is empty instead of containing the appropriate segment.

**Comment by glenfarclas17** [comment]
Thanks for finding and reporting this!  Fixed in v0.7.0!
