### ISSUE TITLE
Not able to connect to JSS::API

### ISSUE THREAD

**Issue by Himanshu3891** [PixarAnimationStudios/ruby-jss#16]
I have been trying to start with a script for JSS but keep getting error when i try to connect to API using JSS::API.connect. 
Mostly I am using wrong jss_server_name. our configurations are hosted on https://eligible.jamfcloud.com. Pasting the exception here. can I get some help there ? 

-------
2.2.3 :004 > JSS::API.connect user:'himanshu', pw: :prompt, server: 'eligible.jamfcloud.com'
Enter the password for JSS user himanshu@eligible.jamfcloud.com: 
eligible.jamfcloud.com
RestClient::RequestTimeout: Request Timeout
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/rest-client-1.8.0/lib/restclient/request.rb:427:in `rescue in transmit'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.7.0/lib/jss/api_connection.rb:303:in `get_rsrc'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.7.0/lib/jss/server.rb:86:in `initialize'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.7.0/lib/jss/api_connection.rb:228:in `new'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.7.0/lib/jss/api_connection.rb:228:in `connect'
	from (irb):4
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.2.3 :005
----------

**Comment by glenfarclas17** [comment]
From poking around it looks like your JSS is served on port 443, rather than the default Jamf port 8443.

Try specifying the port in the connect command, like this:

`JSS::API.connect user:'himanshu', pw: :prompt, server: 'eligible.jamfcloud.com', port: 443`

Let me know if that makes a difference.

Cheers,
-Chris

**Comment by Himanshu3891** [comment]
Thanks Chris. that worked.
