### ISSUE TITLE
cannot load such file -- english on CI environment 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [PixarAnimationStudios/ruby-jss#19]
Hi, 

I am trying to include this gem in my code and it fails on CI environment. I did some research and looks like https://stackoverflow.com/questions/27294172/loaderror-cannot-load-such-file-english is the issue I am facing. can you please check ? Pasting the error below. 

Thanks
Himanshu 

RAILS_ENV=test_migration bundle exec rake db:migrate
/home/ubuntu/security-console/config/application.rb:14: warning: already initialized constant Eligible::ENVIRONMENT
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/bundler/gems/commons-be69a71ea845/lib/commons/eligible_env.rb:10: warning: previous definition of ENVIRONMENT was here
rake aborted!
LoadError: cannot load such file -- english
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/ruby-jss-0.9.2/lib/jss.rb:55:in `<module:JSS>'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/ruby-jss-0.9.2/lib/jss.rb:29:in `<top (required)>'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/ruby-jss-0.9.2/lib/ruby-jss.rb:2:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/home/ubuntu/security-console/config/application.rb:23:in `<top (required)>'
/home/ubuntu/security-console/Rakefile:4:in `require_relative'
/home/ubuntu/security-console/Rakefile:4:in `<top (required)>'
/home/ubuntu/security-console/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/bin/bundle:23:in `load'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

RAILS_ENV=test_migration bundle exec rake db:migrate returned exit code 1

Action failed: RAILS_ENV=test_migration bundle exec rake db:migrate

**Comment by glenfarclas17** [comment]
I don't have a CI environment to test with, so could you test it by changing line 55 of `.../ruby-jss/lib/jss.rb`  from `  require 'english'` to `  require 'English'`.  
If that fixes it for you I'll add the change here.
Thanks!
-Chris

**Comment by HIMANSHU-ELIGIBLE** [comment]
Thanks @glenfarclas17 I have tested it and PR is at https://github.com/PixarAnimationStudios/ruby-jss/pull/20

**Comment by HIMANSHU-ELIGIBLE** [comment]
Thanks for merging PR @glenfarclas17 . Would it be possible to release a gem version with this fix, I would prefer not to point our application to master due to volatile nature of master branch.

**Comment by glenfarclas17** [comment]
Its available as 0.10.0a2,  there are other APIConnection changes in there that need more testing before its released as 0.10.0 - but my tests so far have been good (I'm just checking for things I've missed) To get it from rubygems.org you'll need to specify the version, since it's pre-release. Feel free to report back any problems.
