### ISSUE TITLE
Getting error while accessing smart group 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [PixarAnimationStudios/ruby-jss#21]
getting below error while trying to fetch a smartgroup --- 

----------------------
**[2] pry(main)> JSS::ComputerGroup.fetch name: "Smart group"** 
TypeError: class or module required
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object/criteriable/criteria.rb:97:in `kind_of?'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object/criteriable/criteria.rb:97:in `criteria='
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object/criteriable/criteria.rb:81:in `initialize'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object/criteriable.rb:145:in `new'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object/criteriable.rb:145:in `parse_criteria'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object.rb:889:in `initialize_criteria'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object.rb:828:in `parse_init_data'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object.rb:597:in `initialize'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/ruby-jss-0.10.0a2/lib/jss/api_object/group.rb:146:in `initialize'
/Users/Himanshu/git/security/security-console/lib/jss_helper.rb:13:in `new'
/Users/Himanshu/git/security/security-console/lib/jss_helper.rb:13:in `get_computers_in_smart_group'
/Users/Himanshu/git/security/security-console/lib/tasks/jamf_helper.rake:4:in `block (2 levels) in <top (required)>'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/Himanshu/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => jamf_helper:store_extension_attribute_values
(See full trace by running task with --trace)
-------------------------------------------------

**Comment by glenfarclas17** [comment]
Should be fixed in 0.10.0a3, now available as pre-release on rubygems.org and here!

I have no idea why that suddenly broke, its unrelated to all the recent changes. But I fixed the line in question and it seems to be OK here now.  Thanks for reporting it and let me know if the fix works for you.
Cheers,
-Chris

**Comment by HIMANSHU-ELIGIBLE** [comment]
Thanks. it worked now.

**Comment by glenfarclas17** [comment]
Fixed in 0.10.0
