### ISSUE TITLE
Error undefined method `set_device_mame' for #<JSS::MobileDevice>

### ISSUE THREAD

**Issue by csfjeff** [PixarAnimationStudios/ruby-jss#23]
I'm getting an error message when I try to change the name of an Apple TV using name="new name" - but the error says there is no method 'set_device_mame' - should this be name rather than mame?  It looks like the code is line 527 of lib/jss/api_object/mobile_device.rb

**Comment by glenfarclas17** [comment]
Thanks for reporting this!  You're totally right, but not only is it a typo, it should be calling the `set_name` method from the MDM module. (which I've just aliased to 'set_device_name' for good measure.

I have some other changes to push out within a few days, prob. Monday.  I'll include this.

Cheers!
-Chris

**Comment by csfjeff** [comment]
Nice! Thanks for the quick response :).

**Comment by glenfarclas17** [comment]
Closing this cuz it was fixed in v0.12.0 :-)
