### ISSUE TITLE
A modified Apache 2.0 license cannot be called apache anymore

### ISSUE THREAD

**Issue by pombredanne** [PixarAnimationStudios/ruby-jss#27]
Your use of a modified Apache license is IMHO misleading (it trips license detection tools for instance) ... and I am not sure your [notice](https://github.com/PixarAnimationStudios/ruby-jss/blob/80eca1671299fda2f3171aba2d5001657e14d47c/ruby-jss.gemspec) complies with the license modification conditions at http://www.apache.org/foundation/license-faq.html#mod-license

> May I re-use (and modify) the Apache License 2.0 itself?¶

[...]
> And if you adapt the agreement for your purposes, you have to make sure that the phrase 'Apache License', 'Apache', or any confusingly similar references or parts that specifically refer to the Apache organization do not appear in your version of the license (except to note that your version is derived and differs from the original provided by the ASF).

Your notice starts with 
> Licensed under the Apache License, Version 2.0 (the "Apache License") ...

Could you avoid to call this Apache 2.0 in your notices because it is modified and no longer the standard Apache?  This would promote clarity. (and as a side note your notice requires extra work for license detection tools like the one I maintain to make sure it is not mis-qualified as a standard Apache 2.0)

Thank you for you kind consideration!

**Comment by glenfarclas17** [comment]
Thanks for the feedback. I will forward this to our legal department.

**Comment by pombredanne** [comment]
@glenfarclas17 great!

FWIW, if you wonder why I discovered this issue in the first place: I maintain a decently popular tool to detect licenses at https://github.com/nexB/scancode-toolkit ... it was tripped to report a plain Apache 2.0 license (though with a lower score)  in these [scan results](https://github.com/PixarAnimationStudios/ruby-jss/files/2423390/pixar.txt) while scanning your code in this repo. (and based on what I can see, the same likely applies to the five other repos you have using this license)

For reference, I recall dealing with a vaguely similar issue here https://github.com/palantir/blueprint/issues/2602 that was eventually resolved here https://github.com/palantir/blueprint/pull/2638

And do not hesitate to pass my contact info to your legal department if they need to discuss this.

**Comment by glenfarclas17** [comment]
The gemspec file now lists license as 'NonStandard'.  The title of the LICENSE.txt file 'Modified Apache 2.0 License' is accurate.

**Comment by tdunning** [comment]
THis is still a violation of the Apache trademark.

Please re-open and fix this issue.
