### ISSUE TITLE
[BUG] - JSS::Script.category nil, when category is set

### ISSUE THREAD

**Issue by cybertunnel** [PixarAnimationStudios/ruby-jss#29]
When using `JSS::Script.category`, it returns nil instead of the category name.

*Example*:
``` ruby
script = JSS::Script.fetch name: 'Test script'
category = script.category # sets to nil
puts category

category = script.category_name #sets to the actual name
puts category
```

_**This is a bug from the change over to Categorizable, and `category` was left behind.**_ - use `category_name` instead.

**Comment by glenfarclas17** [comment]
Just cleaning up, this was fixed in 8e415f0e
