### ISSUE TITLE
Policy frequency of "Once per user per computer" not supported

### ISSUE THREAD

**Issue by cybertunnel** [PixarAnimationStudios/ruby-jss#32]
When setting a policy's frequency, these are the options:
` New frequency must be one of :ongoing, :once_per_computer, :once_per_user, :daily, :weekly, :monthly`

However, some policies in Jamf have a `Once per user per computer" text when read.
Any way to set this using `ruby-jss`?

**Comment by glenfarclas17** [comment]
shoud be there now in 1.1.0b2, commit b9d7cf91   `:once_per_user_per_computer`

**Comment by glenfarclas17** [comment]
was fixed in b9d7cf91
