### ISSUE TITLE
Can't Create Advanced Computer Search with blank criteria

### ISSUE THREAD

**Issue by cybertunnel** [PixarAnimationStudios/ruby-jss#42]
When trying to save an AdvancedComputerSearch object with a blank criteria, it errors out with `JSS::MissingDataError` which then states criteria can't be empty, but when dealing with the API directly, you can send `<criteria />` to set the criteria as empty.

Possibly detect that the object is empty, and set the xml to reflect the above xml entry.

**Comment by glenfarclas17** [comment]
Fixed in 0abd296df
