### ISSUE TITLE
Unable to change port with SSL

### ISSUE THREAD

**Issue by wuntee** [PixarAnimationStudios/ruby-jss#5]
It is not possible to set a new port AND use SSL with the `JSS::API.connect` method. This is due to the following in api_connect.rb:

      # ssl or not?
      ssl = SSL_PORT == args[:port].to_i ? "s" : ''
      @rest_url = URI::encode "http#{ssl}://#{args[:server]}:#{args[:port]}/#{RSRC}"

Ideally, there would be a flag that can be passed in `connect` to be able to enable/disable SSL.

**Comment by glenfarclas17** [comment]
Thanks for the report!  I've just added args[:use_ssl] to fix this.
If you supply an non-standard port, you have to specify :use_ssl to be false (defaults to true)
The standard JSS ssl port 8443 is always treated as ssl.

```ruby
      # we're using ssl if 1) args[:use_ssl] is anything but false
      # or 2) the port is the default casper ssl port.
      args[:use_ssl] = true if args[:use_ssl].nil? or args[:port] == SSL_PORT
      
      # and here's the URL
      ssl =  args[:use_ssl] ? "s" : ''
      @rest_url = URI::encode "http#{ssl}://#{args[:server]}:#{args[:port]}/#{RSRC}"
```

I'll get the changed pushed in a few..
Cheers,
-Chris

**Comment by glenfarclas17** [comment]
Oops, this was resolved months go... :-)
