### ISSUE TITLE
A modified Apache 2.0 license is a trademark violation

### ISSUE THREAD

**Issue by tdunning** [PixarAnimationStudios/ruby-jss#86]
Using the name "Apache" to describe your license is a violation of the Apache Software Foundation trademarks.

This license should have a different name.

**Comment by glenfarclas17** [comment]
Thank you for raising this issue. It was presented to our Legal team, and after reviewing, we disagree with your assessment.

**Comment by tdunning** [comment]
Well, the Apache Software Foundation, who own the trademarks disagrees with that assessment.

**Comment by glenfarclas17** [comment]
While we continue to disagree with this assessment, we do want to have your concerns addressed.  As such, we have escalated this matter within our organization so that we can hopefully come to an acceptable resolution.

**Comment by tdunning** [comment]
A very simple resolution is to change the name of the license to something
like the "Pixar Open Source License". You can describe what that means in
the README.

If it is thought that using the Apache name in your license file is
important, then that is evidence that it is Apache's name that you want to
use. And that is what trademarks protect.

The fact is, though, your language is causing Github to mislabel your
software as "Apache Licensed".  That isn't true and it is misleading. The
value of a known license is easy approval by corporate lawyers. This isn't
a known license and it should require approval. Representing it otherwise
is a problem.
