### ISSUE TITLE
Unable to create user with nil LDAP server value

### ISSUE THREAD

**Issue by aaron-mmt** [PixarAnimationStudios/ruby-jss#87]
> [27, 36] in /Users/aaron/JamfTools/UpdateUsersFromCSV.rb
>    27:
>    28: begin
>    29:     x = JSS::User.make(name: "ignoreme")
>    30: rescue Exception => e
>    31:     byebug
> => 32:     puts e.message
>    33: end
>    34: byebug
> (byebug) e
> #<NoMethodError: undefined method `[]' for nil:NilClass>
> (byebug) e.backtrace
> ["/Users/aaron/Work/ruby-jss/lib/jss/api_object/user.rb:171:in `initialize'", "/Users/aaron/Work/ruby-jss/lib/jss/api_object.rb:992:in `new'", "/Users/aaron/Work/ruby-jss/lib/jss/api_object.rb:992:in `new'", "/Users/aaron/Work/ruby-jss/lib/jss/api_object.rb:979:in `make'", "./UpdateUsersFromCSV.rb:29:in `<main'"]
> (byebug) c

user.rb initialize methods assumes that a valid LDAP server value will be provided. As this does not apply to my environment, I don't have a value to provide. Pull request with fix forthcoming.

**Comment by glenfarclas17** [comment]
Fixed in 75bc784, THanks so much! Hoping to release within a couple days
