### ISSUE TITLE
Unable to add new restricted software policy

### ISSUE THREAD

**Issue by marekluban** [PixarAnimationStudios/ruby-jss#90]
👋 I'm running into issues with created a new restricted software policy. My code is:

```
restricted_software = JSS::RestrictedSoftware.make(name: 'Test Restriction')
restricted_software.process_name = 'App'
restricted_software.save
```

And the error received is:

```
undefined method `add_self_service_xml' for #<JSS::RestrictedSoftware:0x00007f7fb74c04a8> (NoMethodError)
```

Which looks to be on this [line](https://github.com/PixarAnimationStudios/ruby-jss/blob/master/lib/jss/api_object/restricted_software.rb#L190) inherited from [module SelfServable](https://github.com/PixarAnimationStudios/ruby-jss/blob/e6d48dd8c77f9275c76787d60d3472615fcd9b77/lib/jss/api_object/self_servable.rb#L818).

I don't see it included in the [RestrictedSoftware class](https://github.com/PixarAnimationStudios/ruby-jss/blob/master/lib/jss/api_object/restricted_software.rb#L35) however I see it in the [Policy class](https://github.com/PixarAnimationStudios/ruby-jss/blob/master/lib/jss/api_object/policy.rb#L78), so I'm thinking maybe this is the issue.

**Comment by glenfarclas17** [comment]
Heya Marek!   I'll take a look at it asap.  I suspect its just techdebt - we haven't really used the RestrictedSoftware class in many years.   

And apologies to everyone for not releasing many updates lately - "real work" (the kind they pay me for) has kinda dominated my life for the past 18 months. 

Cheers,
-Chris

**Comment by glenfarclas17** [comment]
HI Again Marek!

I just looked at it and - that line you mention (line 190 of 'restricted_software.rb') shouldn't even be there!   Just delete it and `restricted_software.save`  should work fine.  

Restricted software items don't show up in self service, so I'm not sure why that line would have ever been there - probably just a copy/paste error from years back.

I'll get that and a few other updates released within the next week.

Thanks for reporting this.!
-Chris

**Comment by marekluban** [comment]
Thanks Chris! Really appreciate all the work you do on this gem - it's helped our team immensely.

In the future I hope to learn more about gems so I can help contribute :)

**Comment by glenfarclas17** [comment]
Heya Marek!

I'm always glad to hear its helping folks,  and good to know your team is still using it :-) 

If you ever want to contribute and have questions, just let me know.

I just pushed out v1.6.4 which includes this change - let me know if it works for you and I'll close this issue.

Cheers!
-Chris
