### ISSUE TITLE
ArgumentError when calling APIObject#fetch in APIObject#initialize

### ISSUE THREAD

**Issue by sailedeer** [PixarAnimationStudios/ruby-jss#91]
Here's the error I'm receiving:
```
/path/to/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ruby-jss-1.6.4/lib/jss/api_object.rb:1093:in 'initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /path/to/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ruby-jss-1.6.4/lib/jss/api_object/script.rb:137:in 'initialize'
        from /path/to/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ruby-jss-1.6.4/lib/jss/api_object.rb:992:in 'new'
        from /path/to/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ruby-jss-1.6.4/lib/jss/api_object.rb:992:in 'new'
        from /path/to/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ruby-jss-1.6.4/lib/jss/api_object.rb:852:in 'fetch'
```

I'm just getting familiar with this project, but I have been able to replicate the error using `irb`. I can verify that I'm connected to my JSS instance, with an API user that has the proper privileges. I'm attempting to fetch a script object with its name, which I know exists with that name on the JSS, and I receive the above error. I've also tried using the id as the fetch identifier, and calling fetch to retrieve a policy object and the result is the same. Any insight would be extremely helpful, and please let me know if there is more information I can include.

**Comment by glenfarclas17** [comment]
Hi  There!

Can you show me  the actual line thats generating that error?  I haven't done much testing in ruby 3 yet, so hopefully that isn't the issue!

FWIW, this syntax works in ruby 2.7:   

 `myscript = JSS::Script.fetch name: 'script-name'` 
 `myscript = JSS::Script.fetch id: 123` 
  
Cheers,
-Chris

**Comment by sailedeer** [comment]
Hi Chris,

Thanks so much for the quick reply! The line that generates the error is as follows:

`script = JSS::Script.fetch(name: 'script_name')`

As far as I can tell, that's exactly the right syntax, but I've made silly mistakes before. However, I just installed Ruby 2.7.5 into my environment, and no longer get the Argument Error so it seems the version might indeed be the issue. Thanks for the heads up on that!

**Comment by glenfarclas17** [comment]
Thanks for the update!

Alas, testing/porting to Ruby 3 has been on the todo list for a while, but for some reason (!) the past 20 months or so have been pretty overwhelming with other work, so ruby-jss has taken a hit in our ability to update it.

I think the method-arugment changes will be the biggest pain as we move to 3 - this kinda confirms that!

Thanks again, and if you want to fork and start playing with ruby 3 changes, feel free, we'd love any help we can get :-) 
-Chris

**Comment by glenfarclas17** [comment]
Gonna close this and make an issue for getting things working in Ruby 3.
