### ISSUE TITLE
Dependency on outdated faraday breaks any modern application integration

### ISSUE THREAD

**Issue by rorra** [PixarAnimationStudios/ruby-jss#96]
The current gem depends on [faraday 1.0.0](https://github.com/PixarAnimationStudios/ruby-jss/blob/master/ruby-jss.gemspec#L71), which dates back to January 22th 2020.

Most of the current ruby gems that depends on faraday, are using faraday 2.00 and upper, in special gems that supports ruby 3.2.0

Is there any plan to migrate the current gem to use a more recent version of faraday, which is used by many modern/updated gems nowdays?

**Comment by glenfarclas17** [comment]
Hi and thanks for the nudge about this.  It's been on my todo list for a while, but as usual, other things are always higher-priority it seems.

But now that I know someone needs it, I'll get it done as soon as I can. 

Cheers,
-Chris

**Comment by rorra** [comment]
Hi Chris

Any idea on how to get a jamf account for testing? I started to work on a PR for the faraday update, but cannot use the company I work for account as it has a production setup and I'm totally forbidden of doing any updates on the company account: https://github.com/rod-eligible/ruby-jss/commit/043e1b8e3873f2b2a1f415ef5f05ea83889eae15

I just submited a trial request to jamf stating that I'm checking the gem update to Faraday 2.0, hopefully they will get me approved (not sure if you are related to jamf company)

**Comment by glenfarclas17** [comment]
Hi Rodrigo, 

I don't have any official connection with Jamf, but they should be able to get you set up with a cloud-based server for that kind of testing.  I know we have used them in the past. 

As for ruby-jss, I just uploaded v5.0.0b2 to rubygems.org - it requires Faraday ~>2.0   and seems to work in my initial tests. To install it yourself, try `gem install ruby-jss --pre`  and let me know what you see.

Mostly I just had to change the method calls that do authentication, and stop using the old `faraday_middleware` gem in favor of the more specific `faraday-multipart` gem, for doing uploads to the `fileuploads` end point.

Let me know what you find! 
- Chris

**Comment by glenfarclas17** [comment]
The new version has been released!  Its actually v4.1.0,  no need to take it to 5.0.0 yet :-)  But it requires faraday ~>2.0 - we are using it with 2.8, since 2.9 requires ruby 3.0 and up, and we won't be making that jump til later this year.

Let me know if you have any problems with it!
Cheers,
- Chris

**Comment by rorra** [comment]
it looks great, thank you 👍
